DROP TABLE IF EXISTS posts;

CREATE TABLE posts(
 title  TEXT NOT NULL,
 content TEXT NOT NULL,
 created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 picture BLOB
);